version: '3.3'

services:
  users:
    build:
      context: ./users_service
      dockerfile: Dockerfile.prod
    expose:
      - 80
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/test
    depends_on:
      - db

  profile:
    build:
      context: ./profile_service
      dockerfile: Dockerfile.prod
    expose:
      - 80
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/test
    depends_on:
      - db

  emails:
    build:
      context: ./emails_service
      dockerfile: Dockerfile.prod
    expose:
      - 80
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/test
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    command: postgres -c 'max_connections=500'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - users
      - profile
      - emails

volumes:
  postgres_data: